export const dietTypeNames = [
  "Vegan",
  "Vegetarian",
  "Lacto Vegetarian",
  "Ovo Vegetarian",
  "Lacto-Ovo Vegetarian",
  "Pescatarian",
  "Flexitarian",
  "Ketogenic (Keto)",
  "Paleo",
  "Gluten-Free",
  "Low Carb",
  "High Protein",
  "Low Fat",
  "DASH",
  "Mediterranean",
  "Whole30",
  "Intermittent Fasting",
  "Carnivore",
  "Raw Food",
  "Zone Diet",
  "Alkaline Diet",
  "Low FODMAP",
  "Detox",
];
