export const dislikeIngredientNames = [
  "Olives",
  "Mushrooms",
  "Cilantro",
  "Anchovies",
  "Eggplant",
  "Liver",
  "Radishes",
  "Ginger",
  "Blue Cheese",
  "Horseradish",
  "Pineapple",
  "Mustard",
  "Pickles",
  "Cabbage",
  "Cauliflower",
  "Carrots",
  "Zucchini",
  "Sweet Potatoes",
  "Asparagus",
  "Tomatoes",
  "Avocado",
  "Chili Peppers",
  "Cucumber",
  "Pecans",
  "Tuna",
  "Coconut",
];
